name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-clippy:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Running clippy
      uses: ./.github/actions/rust-cargo-run
      with:
        command: clippy
        args: --all --all-targets -- -D warnings
        components: clippy
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
